databases:
  - name: ml-dashboard-db
    databaseName: ml_dashboard
    user: ml_user

services:
  - type: web
    name: ml-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 --threads 10 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: ml-dashboard-db
          property: connectionString
